# Battle Insurance Fraud with Text Mining and Data Science {#Insurance-Fraud}

#### Abstract {-}

(ref:abs1)

#### Keywords {-}

insurance, fraud, solution, real-time, text mining, data science


## Insurance Fraud: Issues and Challenges

According to the latest report from Insurance Information Institute, property/casualty insurance fraud costs insurers about $34 billion per year, which is about 10% of the industry’s incurred losses and loss adjustment expenses [@noauthor_facts_nodate]. Any insurer who can accurately identify fraudulent claims will be able to eliminate fraudulent payments and reduce the total cost of insurance. Correspondingly, the premium charged to an average policyholder will be lowered considerably, gaining a competitive advantage for the company.

Currently, fraud detection specialists are hired to review claim files and cross-reference with Insurance Services Office (ISO) data and National Insurance Crime Bureau (NICB) alerts in order to determine fraudulent claims. This process is very manual and time consuming. In addition, statisticians are tasked with building statistical models to identify common characteristics of fraud. Unfortunately, only a limited number of claims attributes are inputted in the database by claims adjusters, which are then available for modeling. As a result, those traditional models only utilized a fraction of claims information and have high false positives and false negatives. Up until now, we lack efficient and accurate ways to detect insurance fraud. Analyzing the phone calls between claimants and claims adjusters using text mining and data science techniques can be a practical and efficient way to detect insurance fraud.


## Detect Insurance Fraud with ALL the Information You've Got On the Fly

The phone calls between claimants and claims adjusters have been monitored and recorded by insurers for quality and training purposes for many years now. These phone calls are the primary communication between claimants and insurers, which are readily available for analysis. We should fully utilize information extracted from phone calls in real-time to ensure the validity of claims. 

The conversation between claimants and claims adjusters should be automatically converted to text and stored in the corresponding claim file. Text mining techniques should be applied in real-time to structure the input text (i.e., the conversation) and seek out key words. The key words should be automatically compared against credible sources to confirm the validity of claimants’ statements. For example, if the claimant mentioned weather, his/her statement should be verified against the weather source. As another example, if the claimant mentioned police, an automatic request for police report should be submitted with relevant driver information. Upon receival of filed police report, his/her statement should be cross-examined for any disparity. Using structured text can also facilitate the comparison between this claimant's story and other fraud cases previously identified in the database to find resemblances. This is especially helpful in targeting organized fraud activities. In addition, Sentiment analysis should be performed to identify unusual emotions/tones and look for rehearsed responses. If prior conversations exist, the current conversation should be compared against prior conversations to discover inconsistencies in claimants’ statements. 

The results of text analyses above should be fed into a neural network model to produce a suspicious claim indicator with three levels of severities (mildly suspicious, highly suspicious and fraud detected). The suspicious claim indicator is continuously being updated as the conversation goes on. If a claim is marked as highly suspicious, the claim adjuster is alerted and prompted to ask additional questions.  Claims adjusters are encouraged to provide feedback to the model based on their experience and intuition. Their feedback, weighted based on their historical performance and years of experience, is another important input to the neural network model. 

With thousands of claims being handled every day, text analyses and neural network models can be fine-tuned on the fly and eventually evolve into a system of robust models that can help insurers accurately detect fraudulent claims.


## Improvements Over Existing Fraud Detection Techniques

The proposed solution utilizes text mining and deep learning techniques to automate the fraud detection process, which is more efficient than relying on the manual work conducted by fraud detection specialists. It is also more predictive than traditional statistical models because it incorporates the entire conversation between claimants and claims adjusters into the analyses rather than just using the claim characteristics summarized by claims adjusters. In addition, statisticians work independently from the front-line claims adjusters, and as a result, there is a significant delay in determining fraud and lack of means to request more information.  Under the proposed solution, near-instantaneous feedback from the model guides claims adjusters in gathering additional information that could lead to determination of fraudulent claims. 

However, one potential drawback of using real-time analyses and feedback is that the claim service time may be lengthened if follow-up questions are indicated by the model. This could negatively impact our customer satisfaction in claim handling experience. Hopefully, with ever-improving models, the false positive rates can be minimized, limiting time spent on unnecessary inquiries.
