# Next Generation of Insurance Pricing {#Insurance-Pricing}

#### Keywords {-}

insurance, pricing, smartphone application, driving data, driving behavior, driving environment, new model approach


## Limited Data = Bad Model
Currently, auto insurers collect "static" information about policyholders and use it to price their insurance premiums. The data usually comes in two categories: drivers' characteristics (driver's gender, age, etc.) and vehicle's information (make and model, model year, etc.). Because this type of data is readily available and easily verifiable, it has been used as predictors for insurance losses [@international_casualty_nodate]. Policy characteristics don't change much from year to year, while accidents can be influenced by many factors. It's not theoretically sound to use "static" predictors (i.e. policy characteristics) to predict a moving target (i.e. accidents). By incorporating driving behavior and driving environment into the model, the insurer can more accurately price for individual policyholder’s risk.


## Identify the cause => Gather, model, repeat
One of the primary reasons why only policy characteristics are used in today’s modeling but not accident information is because insurers lack of reliable ways to obtain accident related information, even the exact time and location of the accident cannot always be identified. People don’t always report accidents to their agents or online in a timely manner, and their memory becomes blurry and confused about specific details of accidents the longer they wait. As a result, inaccurate information sometimes gets reported and specifics about accidents are not used for rating.
 
Our solution is to build a smartphone application that collects policyholders’ driving data and use those driving data to price insurance premium. To increase the adoption rate and usage, we should make it as beneficial to the insurer as to the policyholders. The application allows users to pay premium, contact insurance agents, share their location and most importantly report accidents easily and quickly at the scene. With a one-point click, it can automatically send their name, license plate, and current location to the police and request an ambulance or road side assistance if desired. At the same time, this application serves as a more reliable source of accident time/location to the insurer. From the timestamp, the insurer will be able to isolate the driving behavior prior to the accident. Was the driver speeding before the accident? Was the driver right turning without a complete stop? Were drowsy driving patterns detected? Those information is critical in understanding the potential causes of accidents. In addition, weather and traffic conditions can be joined to the driving data to provide additional insight into the accidents. Was it raining when the accident happened? Did the accident occur in a busy interaction? All those data help paint a digital picture of the accident, giving insurers unprecedented knowledge of auto risk in general.

With this level of granular driving/accident data, the insurer can build a machine learning model to analyze the types of driving behavior and environmental factors that contribute to an accident. The accident model is iterative and will continue to refine itself as new data stream in every second. In addition, a time series model should be built to forecast individual policyholder's future driving behavior/environment. The combination of the accident model and time series projection model can be used to calculate the likelihood that an individual policyholder will have an accident in the future as well as to quantify their risk in the form of insurance premium. As the policyholder’s driving habits improve or deteriorate, the premium will be adjusted accordingly.
 

## Individualized Service and Premium to the Benefit of All
This application is beneficial to both policyholders and insurers. It provides policyholders an easy way to report accidents at the scene and alleviates their stress of notifying multiple parties (police, ambulance, road side assistance, insurance agent, etc.). It also allows insurers to better understand the driving behavior and environmental factors contributing to car accidents and build a better model to quantify the risk of each policyholder. Last but not least, this application promotes a safer driving behavior. Knowing that good driving behaviors (e.g., non-speeding, gentle turns) reduce their premium, policyholders are more likely to drive safely.
Unfortunately, not everyone has a smartphone, so this application cannot roll out to every driver on the road. Also, not every policyholder with a smartphone is comfortable with insurers collecting driving data, so data could be subject to self-selection bias.
